<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="referrer" content="no-referrer"><title><?= esc($quote['quote_number']) ?> | <?= esc($business['business_name']) ?></title><link rel="stylesheet" href="<?= esc(base_url('assets/css/app.css'), 'attr') ?>"></head>
<body class="proposal-page">
    <header class="proposal-header"><a href="/" aria-label="<?= esc($business['business_name'], 'attr') ?> home"><?= esc($business['business_name']) ?></a><button type="button" onclick="window.print()">Print / save PDF</button></header>
    <main class="proposal"><section class="proposal-intro"><div><p class="eyebrow">PROJECT QUOTE</p><h1><?= esc($quote['quote_number']) ?></h1><p>Prepared for <strong><?= esc($quote['customer_business_name'] ?: $quote['customer_name']) ?></strong></p></div><dl><dt>Quote date</dt><dd><?= esc($quote['quote_date']) ?></dd><dt>Valid through</dt><dd><?= esc($quote['expires_on']) ?></dd><dt>Status</dt><dd><?= esc(\App\Models\QuoteModel::STATUSES[$displayStatus] ?? ucfirst($displayStatus)) ?></dd></dl></section>
        <section class="proposal-items" aria-labelledby="proposal-scope"><h2 id="proposal-scope">Scope and pricing</h2><div class="proposal-table"><div class="proposal-row proposal-row-head"><span>Description</span><span>Quantity</span><span>Unit price</span><span>Total</span></div><?php foreach ($items as $item): ?><div class="proposal-row"><div><strong><?= esc($item['description']) ?></strong><?php if ($item['details']): ?><p><?= nl2br(esc($item['details'])) ?></p><?php endif ?></div><span data-label="Quantity"><?= esc(number_format((float) $item['quantity'], 2)) ?></span><span data-label="Unit price"><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $item['unit_price'], 2)) ?></span><strong data-label="Total"><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $item['line_total'], 2)) ?></strong></div><?php endforeach ?></div><dl class="proposal-totals"><dt>Subtotal</dt><dd><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['subtotal'], 2)) ?></dd><?php if ((float) $quote['discount_amount'] > 0): ?><dt>Discount</dt><dd>-<?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['discount_amount'], 2)) ?></dd><?php endif ?><?php if ((float) $quote['tax_amount'] > 0): ?><dt>Tax (<?= esc(number_format((float) $quote['tax_rate'], 3)) ?>%)</dt><dd><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['tax_amount'], 2)) ?></dd><?php endif ?><dt class="total">Total</dt><dd class="total"><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['total'], 2)) ?></dd><?php if ((float) $quote['deposit_percentage'] > 0): ?><dt>Deposit required (<?= esc(number_format((float) $quote['deposit_percentage'], 2)) ?>%)</dt><dd><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['deposit_amount'], 2)) ?></dd><?php endif ?></dl></section>
        <?php if ($quote['terms'] || $quote['notes']): ?><section class="proposal-terms"><?php if ($quote['terms']): ?><div><h2>Terms</h2><p><?= nl2br(esc($quote['terms'])) ?></p></div><?php endif ?><?php if ($quote['notes']): ?><div><h2>Notes</h2><p><?= nl2br(esc($quote['notes'])) ?></p></div><?php endif ?></section><?php endif ?>
        <section class="proposal-response" aria-labelledby="proposal-response-title">
            <?php if (session('response_message')): ?><div class="proposal-response-notice" role="status"><?= esc(session('response_message')) ?></div><?php endif ?>
            <?php if (session('response_error')): ?><div class="proposal-response-notice proposal-response-error" role="alert"><?= esc(session('response_error')) ?></div><?php endif ?>
            <?php if ($canRespond): ?>
                <div><p class="eyebrow">YOUR DECISION</p><h2 id="proposal-response-title">Ready to move forward?</h2><p>Accepting confirms this scope and pricing. Payment is not collected on this page.</p></div>
                <form action="/proposal/<?= esc($quote['access_token'], 'attr') ?>/respond" method="post">
                    <?= csrf_field() ?>
                    <label for="response-note">Optional note</label>
                    <textarea id="response-note" name="response_note" maxlength="1000" rows="4" placeholder="Add a scheduling note or a brief reason for declining."></textarea>
                    <div class="proposal-response-actions"><button class="button button-primary" type="submit" name="decision" value="accepted">Accept quote</button><button class="button button-secondary" type="submit" name="decision" value="declined" onclick="return confirm('Decline this quote? This response cannot be changed from this page.')">Decline quote</button></div>
                </form>
            <?php elseif ($displayStatus === 'accepted'): ?>
                <div><p class="eyebrow">ACCEPTED</p><h2 id="proposal-response-title">This quote has been accepted.</h2><p>The studio has your decision and will follow up with project scheduling and next steps.</p><?php if ($quote['customer_response_note']): ?><blockquote><?= nl2br(esc($quote['customer_response_note'])) ?></blockquote><?php endif ?></div>
            <?php elseif ($displayStatus === 'declined'): ?>
                <div><p class="eyebrow">DECLINED</p><h2 id="proposal-response-title">This quote has been declined.</h2><p>The response is recorded. Contact the studio directly if circumstances have changed.</p><?php if ($quote['customer_response_note']): ?><blockquote><?= nl2br(esc($quote['customer_response_note'])) ?></blockquote><?php endif ?></div>
            <?php else: ?>
                <div><p class="eyebrow">EXPIRED</p><h2 id="proposal-response-title">This quote is no longer open for a response.</h2><p>Contact the studio for refreshed dates or a revised scope.</p></div>
            <?php endif ?>
        </section>
        <footer class="proposal-footer"><strong><?= esc($business['business_name']) ?></strong><p>This quote is valid through <?= esc($quote['expires_on']) ?>. Reply to your quote email with questions or requested changes.</p></footer>
    </main>
</body>
</html>
