<?= view('admin/partials/shell_start', ['pageTitle' => $service === null ? 'Add service' : 'Edit service', 'activeSection' => 'services', 'businessName' => $businessName]) ?>
<main class="admin-main">
    <a class="admin-back-link" href="/admin/services">&larr; Services</a>
    <div class="admin-page-heading"><div><p class="admin-kicker">SERVICE CATALOG</p><h1><?= $service === null ? 'Add service' : 'Edit service' ?></h1><p>Only published services appear on the public website.</p></div></div>
    <?php $errors = session('errors') ?? []; ?>
    <?php if ($errors !== []): ?><div class="notice notice-error" role="alert">Please review the highlighted fields.</div><?php endif ?>
    <form class="admin-form" action="<?= $service === null ? '/admin/services' : '/admin/services/' . (int) $service['id'] ?>" method="post">
        <?= csrf_field() ?>
        <section class="admin-form-section" aria-labelledby="service-content-heading"><div class="admin-form-section-heading"><h2 id="service-content-heading">Service details</h2><p>What visitors need to understand about this service.</p></div><div class="admin-form-fields">
            <div class="form-row"><label for="name">Service name</label><input id="name" name="name" maxlength="120" required value="<?= esc(old('name', $service['name'] ?? ''), 'attr') ?>"><?php if (isset($errors['name'])): ?><p class="field-error"><?= esc($errors['name']) ?></p><?php endif ?><?php if ($service !== null): ?><p class="field-help">Public URL: /services/<?= esc($service['slug']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="summary">Short description</label><textarea id="summary" name="summary" maxlength="300" rows="3" required><?= esc(old('summary', $service['summary'] ?? '')) ?></textarea><?php if (isset($errors['summary'])): ?><p class="field-error"><?= esc($errors['summary']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="description">Full description</label><textarea id="description" name="description" maxlength="10000" rows="7" required><?= esc(old('description', $service['description'] ?? '')) ?></textarea><?php if (isset($errors['description'])): ?><p class="field-error"><?= esc($errors['description']) ?></p><?php endif ?></div>
        </div></section>
        <section class="admin-form-section" aria-labelledby="pricing-heading"><div class="admin-form-section-heading"><h2 id="pricing-heading">Starting price</h2><p>Optional guidance, not a final quote.</p></div><div class="admin-form-fields"><div class="form-grid"><div class="form-row"><label for="starting_price">Amount</label><input id="starting_price" name="starting_price" type="number" min="0" max="99999999.99" step="0.01" value="<?= esc(old('starting_price', $service['starting_price'] ?? ''), 'attr') ?>"><?php if (isset($errors['starting_price'])): ?><p class="field-error"><?= esc($errors['starting_price']) ?></p><?php endif ?></div><div class="form-row"><label for="currency_code">Currency code</label><input id="currency_code" name="currency_code" minlength="3" maxlength="3" required value="<?= esc(old('currency_code', $service['currency_code'] ?? 'USD'), 'attr') ?>"><p class="field-help">For example, USD or CAD.</p><?php if (isset($errors['currency_code'])): ?><p class="field-error"><?= esc($errors['currency_code']) ?></p><?php endif ?></div></div><div class="form-row"><label class="checkbox-label"><input type="hidden" name="show_price" value="0"><input type="checkbox" name="show_price" value="1" <?= old('show_price', $service['show_price'] ?? 0) ? 'checked' : '' ?>> Show starting price publicly</label></div></div></section>
        <section class="admin-form-section" aria-labelledby="publishing-heading"><div class="admin-form-section-heading"><h2 id="publishing-heading">Publishing</h2><p>Control visibility and listing order.</p></div><div class="admin-form-fields"><div class="form-grid"><div class="form-row"><label for="status">Status</label><select id="status" name="status"><?php foreach (['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'] as $value => $label): ?><option value="<?= $value ?>" <?= old('status', $service['status'] ?? 'draft') === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><?php if (isset($errors['status'])): ?><p class="field-error"><?= esc($errors['status']) ?></p><?php endif ?></div><div class="form-row"><label for="sort_order">Display order</label><input id="sort_order" name="sort_order" type="number" min="0" step="1" required value="<?= esc(old('sort_order', $service['sort_order'] ?? 0), 'attr') ?>"><?php if (isset($errors['sort_order'])): ?><p class="field-error"><?= esc($errors['sort_order']) ?></p><?php endif ?></div></div></div></section>
        <div class="admin-form-actions"><a href="/admin/services">Cancel</a><button class="admin-primary-action" type="submit">Save service</button></div>
    </form>
</main>
<?= view('admin/partials/shell_end') ?>
