<?= view('admin/partials/shell_start', ['pageTitle' => $customer === null ? 'Add customer' : 'Edit customer', 'activeSection' => 'customers', 'businessName' => $businessName]) ?>
<main class="admin-main">
    <a class="admin-back-link" href="<?= $customer === null ? '/admin/customers' : '/admin/customers/' . (int) $customer['id'] ?>">&larr; <?= $customer === null ? 'Customers' : 'Customer profile' ?></a>
    <div class="admin-page-heading"><div><p class="admin-kicker">CUSTOMER RECORD</p><h1><?= $customer === null ? 'Add customer' : 'Edit customer' ?></h1><p>Contact and address details are private workspace information.</p></div></div>
    <?php $errors = session('errors') ?? []; ?>
    <?php if ($errors !== []): ?><div class="notice notice-error" role="alert">Please review the highlighted fields.</div><?php endif ?>
    <form class="admin-form" action="<?= $customer === null ? '/admin/customers' : '/admin/customers/' . (int) $customer['id'] ?>" method="post">
        <?= csrf_field() ?>
        <section class="admin-form-section" aria-labelledby="identity-heading"><div class="admin-form-section-heading"><h2 id="identity-heading">Identity</h2><p>The person and business name used throughout the workspace.</p></div><div class="admin-form-fields"><div class="form-grid"><div class="form-row"><label for="name">Contact name</label><input id="name" name="name" maxlength="120" required value="<?= esc(old('name', $customer['name'] ?? ''), 'attr') ?>"><?php if (isset($errors['name'])): ?><p class="field-error"><?= esc($errors['name']) ?></p><?php endif ?></div><div class="form-row"><label for="business-name">Business name</label><input id="business-name" name="business_name" maxlength="160" value="<?= esc(old('business_name', $customer['business_name'] ?? ''), 'attr') ?>"><?php if (isset($errors['business_name'])): ?><p class="field-error"><?= esc($errors['business_name']) ?></p><?php endif ?></div></div></div></section>
        <section class="admin-form-section" aria-labelledby="contact-heading"><div class="admin-form-section-heading"><h2 id="contact-heading">Contact</h2><p>Email is used to match future quote requests to this relationship.</p></div><div class="admin-form-fields"><div class="form-grid"><div class="form-row"><label for="email">Email</label><input id="email" name="email" type="email" maxlength="254" required value="<?= esc(old('email', $customer['email'] ?? ''), 'attr') ?>"><?php if (isset($errors['email'])): ?><p class="field-error"><?= esc($errors['email']) ?></p><?php endif ?></div><div class="form-row"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" maxlength="40" value="<?= esc(old('phone', $customer['phone'] ?? ''), 'attr') ?>"><?php if (isset($errors['phone'])): ?><p class="field-error"><?= esc($errors['phone']) ?></p><?php endif ?></div></div></div></section>
        <section class="admin-form-section" aria-labelledby="address-heading"><div class="admin-form-section-heading"><h2 id="address-heading">Address</h2><p>Optional billing or business address for future documents.</p></div><div class="admin-form-fields"><div class="form-row"><label for="address-line-1">Address line 1</label><input id="address-line-1" name="address_line_1" maxlength="180" value="<?= esc(old('address_line_1', $customer['address_line_1'] ?? ''), 'attr') ?>"></div><div class="form-row"><label for="address-line-2">Address line 2</label><input id="address-line-2" name="address_line_2" maxlength="180" value="<?= esc(old('address_line_2', $customer['address_line_2'] ?? ''), 'attr') ?>"></div><div class="form-grid"><div class="form-row"><label for="city">City</label><input id="city" name="city" maxlength="120" value="<?= esc(old('city', $customer['city'] ?? ''), 'attr') ?>"></div><div class="form-row"><label for="region">State / region</label><input id="region" name="region" maxlength="120" value="<?= esc(old('region', $customer['region'] ?? ''), 'attr') ?>"></div><div class="form-row"><label for="postal-code">Postal code</label><input id="postal-code" name="postal_code" maxlength="30" value="<?= esc(old('postal_code', $customer['postal_code'] ?? ''), 'attr') ?>"></div><div class="form-row"><label for="country">Country</label><input id="country" name="country" maxlength="120" value="<?= esc(old('country', $customer['country'] ?? ''), 'attr') ?>"></div></div></div></section>
        <section class="admin-form-section" aria-labelledby="notes-heading"><div class="admin-form-section-heading"><h2 id="notes-heading">Internal notes</h2><p>Private context for the studio. Never shown to the customer.</p></div><div class="admin-form-fields"><div class="form-row"><label for="notes">Notes</label><textarea id="notes" name="notes" maxlength="5000" rows="7"><?= esc(old('notes', $customer['notes'] ?? '')) ?></textarea><?php if (isset($errors['notes'])): ?><p class="field-error"><?= esc($errors['notes']) ?></p><?php endif ?></div></div></section>
        <div class="admin-form-actions"><a href="<?= $customer === null ? '/admin/customers' : '/admin/customers/' . (int) $customer['id'] ?>">Cancel</a><button class="admin-primary-action" type="submit">Save customer</button></div>
    </form>
</main>
<?= view('admin/partials/shell_end') ?>
