<?= view('admin/partials/shell_start', ['pageTitle' => $project === null ? 'Add project' : 'Edit project', 'activeSection' => 'portfolio', 'businessName' => $businessName]) ?>
<main class="admin-main">
    <a class="admin-back-link" href="/admin/portfolio">&larr; Portfolio</a>
    <div class="admin-page-heading"><div><p class="admin-kicker">PORTFOLIO</p><h1><?= $project === null ? 'Add project' : 'Edit project' ?></h1><p>Build a case study from real project work.</p></div></div>
    <?php $errors = session('errors') ?? []; ?>
    <?php if ($errors !== []): ?><div class="notice notice-error" role="alert">Please review the highlighted fields.</div><?php endif ?>
    <form class="admin-form" action="<?= $project === null ? '/admin/portfolio' : '/admin/portfolio/' . (int) $project['id'] ?>" method="post" enctype="multipart/form-data">
        <?= csrf_field() ?>
        <section class="admin-form-section" aria-labelledby="project-details-heading"><div class="admin-form-section-heading"><h2 id="project-details-heading">Project details</h2><p>Give visitors enough context to understand the work.</p></div><div class="admin-form-fields">
            <div class="form-row"><label for="title">Project title</label><input id="title" name="title" maxlength="160" required value="<?= esc(old('title', $project['title'] ?? ''), 'attr') ?>"><?php if (isset($errors['title'])): ?><p class="field-error"><?= esc($errors['title']) ?></p><?php endif ?><?php if ($project !== null): ?><p class="field-help">Public URL: /work/<?= esc($project['slug']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="client_name">Client name</label><input id="client_name" name="client_name" maxlength="160" value="<?= esc(old('client_name', $project['client_name'] ?? ''), 'attr') ?>"><p class="field-help">Leave blank if the client should not be named.</p><?php if (isset($errors['client_name'])): ?><p class="field-error"><?= esc($errors['client_name']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="summary">Short summary</label><textarea id="summary" name="summary" maxlength="320" rows="3" required><?= esc(old('summary', $project['summary'] ?? '')) ?></textarea><?php if (isset($errors['summary'])): ?><p class="field-error"><?= esc($errors['summary']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="challenge">The challenge</label><textarea id="challenge" name="challenge" maxlength="10000" rows="5" required><?= esc(old('challenge', $project['challenge'] ?? '')) ?></textarea><?php if (isset($errors['challenge'])): ?><p class="field-error"><?= esc($errors['challenge']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="solution">The solution</label><textarea id="solution" name="solution" maxlength="10000" rows="5" required><?= esc(old('solution', $project['solution'] ?? '')) ?></textarea><?php if (isset($errors['solution'])): ?><p class="field-error"><?= esc($errors['solution']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="project_date">Project date</label><input id="project_date" name="project_date" type="date" value="<?= esc(old('project_date', $project['project_date'] ?? ''), 'attr') ?>"><?php if (isset($errors['project_date'])): ?><p class="field-error"><?= esc($errors['project_date']) ?></p><?php endif ?></div>
        </div></section>
        <section class="admin-form-section" aria-labelledby="project-image-heading"><div class="admin-form-section-heading"><h2 id="project-image-heading">Featured image</h2><p>Required before publishing. This image appears on the public site.</p></div><div class="admin-form-fields">
            <?php if ($currentImage !== null): ?><figure class="admin-current-image"><img src="<?= esc(base_url($currentImage['path']), 'attr') ?>" alt="<?= esc($currentImage['alt_text'], 'attr') ?>"><figcaption>Current image: <?= esc($currentImage['alt_text']) ?></figcaption></figure><?php endif ?>
            <div class="form-row"><label for="featured_media_id">Choose an existing image</label><select id="featured_media_id" name="featured_media_id"><option value=""><?= $project === null ? 'No existing image selected' : 'Keep current image' ?></option><?php foreach ($media as $asset): ?><option value="<?= (int) $asset['id'] ?>" <?= (string) old('featured_media_id', '') === (string) $asset['id'] ? 'selected' : '' ?>><?= esc($asset['alt_text']) ?> (#<?= (int) $asset['id'] ?>)</option><?php endforeach ?></select></div>
            <p class="field-help">Or upload a new image. A new upload takes precedence over the selection above.</p>
            <div class="form-row"><label for="featured_image">Upload image</label><input id="featured_image" name="featured_image" type="file" accept="image/jpeg,image/png,image/webp"><p class="field-help">JPEG, PNG, or WebP; up to 5 MB.</p><?php if (isset($errors['featured_image'])): ?><p class="field-error"><?= esc($errors['featured_image']) ?></p><?php endif ?></div>
            <div class="form-row"><label for="image_alt">Image description</label><input id="image_alt" name="image_alt" maxlength="255" value="<?= esc(old('image_alt', ''), 'attr') ?>"><p class="field-help">Describe a new image for people using screen readers.</p><?php if (isset($errors['image_alt'])): ?><p class="field-error"><?= esc($errors['image_alt']) ?></p><?php endif ?></div>
        </div></section>
        <?php $selectedGalleryIds = old('gallery_media_ids', $galleryMediaIds); $selectedGalleryIds = is_array($selectedGalleryIds) ? array_map('intval', $selectedGalleryIds) : []; $selectedServiceIds = old('service_ids', $projectServiceIds); $selectedServiceIds = is_array($selectedServiceIds) ? array_map('intval', $selectedServiceIds) : []; $oldGalleryOrders = old('gallery_sort_order', $gallerySortOrders); $oldGalleryOrders = is_array($oldGalleryOrders) ? $oldGalleryOrders : []; ?>
        <section class="admin-form-section" aria-labelledby="project-gallery-heading"><div class="admin-form-section-heading"><h2 id="project-gallery-heading">Project gallery</h2><p>Select reusable images and set their display order.</p></div><div class="admin-form-fields admin-form-fields-wide">
            <?php if ($media === []): ?><p class="field-help">Upload images in the <a href="/admin/media">media library</a> first.</p><?php else: ?><div class="admin-media-picker"><?php foreach ($media as $asset): ?><label class="admin-media-choice"><img src="<?= esc(base_url($asset['path']), 'attr') ?>" alt=""><span><input type="checkbox" name="gallery_media_ids[]" value="<?= (int) $asset['id'] ?>" <?= in_array((int) $asset['id'], $selectedGalleryIds, true) ? 'checked' : '' ?>> <?= esc($asset['alt_text']) ?></span><span class="admin-media-order">Order <input name="gallery_sort_order[<?= (int) $asset['id'] ?>]" type="number" min="0" step="1" value="<?= esc($oldGalleryOrders[$asset['id']] ?? 0, 'attr') ?>"></span></label><?php endforeach ?></div><?php endif ?>
            <?php if (isset($errors['gallery_media_ids'])): ?><p class="field-error"><?= esc($errors['gallery_media_ids']) ?></p><?php endif ?><?php if (isset($errors['relationships'])): ?><p class="field-error"><?= esc($errors['relationships']) ?></p><?php endif ?>
        </div></section>
        <section class="admin-form-section" aria-labelledby="project-services-heading"><div class="admin-form-section-heading"><h2 id="project-services-heading">Related services</h2><p>Connect this project to services visitors can explore.</p></div><div class="admin-form-fields"><div class="admin-checkbox-list"><?php foreach ($services as $serviceOption): ?><label class="checkbox-label"><input type="checkbox" name="service_ids[]" value="<?= (int) $serviceOption['id'] ?>" <?= in_array((int) $serviceOption['id'], $selectedServiceIds, true) ? 'checked' : '' ?>> <?= esc($serviceOption['name']) ?> <small><?= esc(ucfirst($serviceOption['status'])) ?></small></label><?php endforeach ?></div><?php if ($services === []): ?><p class="field-help">Add services before linking them to a project.</p><?php endif ?><?php if (isset($errors['service_ids'])): ?><p class="field-error"><?= esc($errors['service_ids']) ?></p><?php endif ?></div></section>
        <section class="admin-form-section" aria-labelledby="project-publishing-heading"><div class="admin-form-section-heading"><h2 id="project-publishing-heading">Publishing</h2><p>Control where and when this project appears.</p></div><div class="admin-form-fields"><div class="form-grid"><div class="form-row"><label for="status">Status</label><select id="status" name="status"><?php foreach (['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'] as $value => $label): ?><option value="<?= $value ?>" <?= old('status', $project['status'] ?? 'draft') === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><?php if (isset($errors['status'])): ?><p class="field-error"><?= esc($errors['status']) ?></p><?php endif ?></div><div class="form-row"><label for="sort_order">Display order</label><input id="sort_order" name="sort_order" type="number" min="0" step="1" required value="<?= esc(old('sort_order', $project['sort_order'] ?? 0), 'attr') ?>"><?php if (isset($errors['sort_order'])): ?><p class="field-error"><?= esc($errors['sort_order']) ?></p><?php endif ?></div></div><div class="form-row"><label class="checkbox-label"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" <?= old('is_featured', $project['is_featured'] ?? 0) ? 'checked' : '' ?>> Feature this project on the homepage</label></div></div></section>
        <div class="admin-form-actions"><a href="/admin/portfolio">Cancel</a><button class="admin-primary-action" type="submit">Save project</button></div>
    </form>
</main>
<?= view('admin/partials/shell_end') ?>
