<?= view('admin/partials/shell_start', ['pageTitle' => 'Quote inbox', 'activeSection' => 'quote-requests', 'businessName' => $businessName]) ?>
<main class="admin-main admin-main-wide">
    <div class="admin-page-heading"><div><p class="admin-kicker">INBOX</p><h1>Quote requests</h1><p>Review project requirements, attachments, and the next action for each inquiry.</p></div></div>
    <div class="admin-list-toolbar"><span><?= count($requests) ?> <?= count($requests) === 1 ? 'request' : 'requests' ?></span><form class="admin-inline-filter" action="/admin/quote-requests" method="get"><label for="quote-status-filter">Status</label><select id="quote-status-filter" name="status" onchange="this.form.submit()"><option value="">All statuses</option><?php foreach ($statuses as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= $selectedStatus === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></form></div>
    <?php if ($requests === []): ?><div class="admin-empty"><h2>No matching requests</h2><p>New quote requests will appear here once visitors submit the builder.</p></div><?php else: ?>
    <div class="admin-service-table-wrap"><table class="admin-service-table"><thead><tr><th scope="col">Client</th><th scope="col">Reference</th><th scope="col">Status</th><th scope="col">Received</th><th scope="col">Action</th></tr></thead><tbody>
        <?php foreach ($requests as $request): ?><tr><td><strong><?= esc($request['name']) ?></strong><small><?= esc($request['company'] ?: $request['email']) ?></small></td><td data-label="Reference"><span class="admin-reference"><?= esc($request['reference_number']) ?></span></td><td data-label="Status"><span class="admin-status admin-status-<?= esc(str_replace('_', '-', $request['status']), 'attr') ?>"><?= esc($statuses[$request['status']] ?? ucfirst($request['status'])) ?></span></td><td data-label="Received"><?= esc(substr($request['created_at'] ?? '', 0, 16)) ?></td><td data-label="Action"><a href="/admin/quote-requests/<?= (int) $request['id'] ?>">Open</a></td></tr><?php endforeach ?>
    </tbody></table></div><?php endif ?>
</main>
<?= view('admin/partials/shell_end') ?>
