<?= view('admin/partials/shell_start', ['pageTitle' => 'Quote request', 'activeSection' => 'quote-requests', 'businessName' => $businessName]) ?>
<main class="admin-main admin-main-wide">
    <a class="admin-back-link" href="/admin/quote-requests">&larr; Quote inbox</a>
    <div class="admin-page-heading admin-quote-heading"><div><p class="admin-kicker"><?= esc($request['reference_number']) ?></p><h1><?= esc($request['name']) ?><?= $request['company'] ? ' / ' . esc($request['company']) : '' ?></h1><p>Received <?= esc($request['created_at']) ?><?php if ($customer): ?> &middot; <a href="/admin/customers/<?= (int) $customer['id'] ?>">Open customer profile</a><?php endif ?></p></div><div class="admin-heading-actions"><span class="admin-status admin-status-<?= esc(str_replace('_', '-', $request['status']), 'attr') ?>"><?= esc($statuses[$request['status']] ?? ucfirst($request['status'])) ?></span><?php if ($quote): ?><a class="admin-primary-action" href="/admin/quotes/<?= (int) $quote['id'] ?>/edit">Open <?= esc($quote['quote_number']) ?></a><?php elseif (in_array($request['status'], \App\Models\QuoteRequestModel::QUOTEABLE_STATUSES, true)): ?><form action="/admin/quote-requests/<?= (int) $request['id'] ?>/quote" method="post"><?= csrf_field() ?><button class="admin-primary-action" type="submit">Create quote</button></form><?php endif ?></div></div>
    <?php if (session('message')): ?><div class="notice" role="status"><?= esc(session('message')) ?></div><?php endif ?>
    <?php if (session('errors')): ?><div class="notice notice-error" role="alert"><?= esc(implode(' ', session('errors'))) ?></div><?php endif ?>
    <div class="admin-quote-grid">
        <div class="admin-quote-record">
            <section><h2>Client and project</h2><dl><dt>Email</dt><dd><a href="mailto:<?= esc($request['email'], 'attr') ?>"><?= esc($request['email']) ?></a></dd><dt>Phone</dt><dd><?= $request['phone'] ? esc($request['phone']) : 'Not provided' ?></dd><dt>Preferred contact</dt><dd><?= esc(ucfirst($request['preferred_contact'])) ?></dd><dt>Desired completion</dt><dd><?= $request['desired_completion_date'] ? esc($request['desired_completion_date']) : 'Not specified' ?></dd><dt>Budget</dt><dd><?= $request['budget_range'] ? esc($request['budget_range']) : 'Not specified' ?></dd></dl><h3>Project summary</h3><p><?= nl2br(esc($request['project_summary'])) ?></p><?php if ($request['additional_notes']): ?><h3>Additional notes</h3><p><?= nl2br(esc($request['additional_notes'])) ?></p><?php endif ?></section>
            <section><h2>Selected services</h2><div class="admin-request-services"><?php foreach ($services as $service): ?><article><div><h3><?= esc($service['service_name']) ?></h3><p><?= esc($service['service_summary']) ?></p></div><?php if ($service['show_price'] && $service['starting_price'] !== null): ?><strong><?= esc($service['currency_code']) ?> <?= esc(number_format((float) $service['starting_price'], 2)) ?></strong><?php endif ?></article><?php endforeach ?></div></section>
            <section><h2>Intake answers</h2><?php if ($answers === []): ?><p>No intake questions were configured.</p><?php else: ?><dl class="admin-answer-list"><?php $currentGroup = null; foreach ($answers as $answer): ?><?php if ($currentGroup !== $answer['group_name']): ?><?php $currentGroup = $answer['group_name']; ?><div class="admin-answer-group"><dt><?= esc($currentGroup) ?></dt><dd></dd></div><?php endif ?><dt><?= esc($answer['question_label']) ?></dt><dd><?= $answer['answer_text'] !== null ? nl2br(esc($answer['answer_text'])) : '<span class="admin-muted">Not answered</span>' ?></dd><?php endforeach ?></dl><?php endif ?></section>
            <?php if ($files !== []): ?><section><h2>Attachments</h2><div class="admin-attachment-list"><?php foreach ($files as $file): ?><a href="/admin/quote-requests/<?= (int) $request['id'] ?>/files/<?= (int) $file['id'] ?>"><span><?= esc($file['original_name']) ?></span><small><?= esc(strtoupper($file['extension'])) ?> &middot; <?= esc(number_format((int) $file['size_bytes'] / 1024, 0)) ?> KB</small></a><?php endforeach ?></div></section><?php endif ?>
        </div>
        <aside class="admin-quote-workflow"><form action="/admin/quote-requests/<?= (int) $request['id'] ?>" method="post"><?= csrf_field() ?><h2>Request workflow</h2><div class="form-row"><label for="status">Status</label><select id="status" name="status"><?php foreach ($statuses as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= old('status', $request['status']) === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></div><div class="form-row"><label for="internal-notes">Internal notes</label><textarea id="internal-notes" name="internal_notes" rows="9" maxlength="5000" placeholder="Private follow-up notes for the studio."><?= esc(old('internal_notes', $request['internal_notes'] ?? '')) ?></textarea></div><button class="admin-primary-action" type="submit">Save workflow</button></form><div class="admin-notification-state"><h2>Notifications</h2><dl><dt>Owner</dt><dd><?= esc(str_replace('_', ' ', ucfirst($request['owner_notification_status']))) ?></dd><dt>Customer</dt><dd><?= esc(str_replace('_', ' ', ucfirst($request['customer_notification_status']))) ?></dd></dl></div></aside>
    </div>
</main>
<?= view('admin/partials/shell_end') ?>
