<?= view('admin/partials/shell_start', ['pageTitle' => 'Edit image', 'activeSection' => 'media', 'businessName' => $businessName]) ?>
<main class="admin-main">
    <a class="admin-back-link" href="/admin/media">&larr; Media library</a>
    <div class="admin-page-heading"><div><p class="admin-kicker">MEDIA</p><h1>Edit image</h1><p>Update accessibility text and review where this image is used.</p></div></div>
    <?php $errors = session('errors') ?? []; ?>
    <?php if (session('message')): ?><div class="notice" role="status"><?= esc(session('message')) ?></div><?php endif ?>
    <?php if ($errors !== []): ?><div class="notice notice-error" role="alert"><?= esc(reset($errors)) ?></div><?php endif ?>
    <div class="admin-media-editor"><figure><img src="<?= esc(base_url($asset['path']), 'attr') ?>" alt="<?= esc($asset['alt_text'], 'attr') ?>"></figure><div><form class="admin-form admin-media-details" action="/admin/media/<?= (int) $asset['id'] ?>" method="post"><?= csrf_field() ?><div class="form-row"><label for="alt_text">Image description</label><input id="alt_text" name="alt_text" maxlength="255" required value="<?= esc(old('alt_text', $asset['alt_text']), 'attr') ?>"><?php if (isset($errors['alt_text'])): ?><p class="field-error"><?= esc($errors['alt_text']) ?></p><?php endif ?></div><dl class="admin-media-facts"><dt>Type</dt><dd><?= esc($asset['mime_type']) ?></dd><dt>Size</dt><dd><?= esc(number_format($asset['byte_size'] / 1024, 0)) ?> KB</dd><dt>Featured projects</dt><dd><?= (int) $usage['featured_projects'] ?></dd><dt>Project galleries</dt><dd><?= (int) $usage['project_galleries'] ?></dd><dt>Services</dt><dd><?= (int) $usage['services'] ?></dd></dl><button class="admin-primary-action" type="submit">Save details</button></form><form class="admin-media-delete" action="/admin/media/<?= (int) $asset['id'] ?>/delete" method="post" onsubmit="return confirm('Delete this image permanently?')"><?= csrf_field() ?><button type="submit" <?= $usage['total'] > 0 ? 'disabled' : '' ?>>Delete image</button><?php if ($usage['total'] > 0): ?><p>Remove all <?= (int) $usage['total'] ?> references before deleting this image.</p><?php else: ?><p>This removes the library record and managed upload file.</p><?php endif ?></form></div></div>
</main>
<?= view('admin/partials/shell_end') ?>
