<?= view('portal/partials/shell_start', ['pageTitle' => 'Overview', 'activeSection' => 'overview', 'businessName' => $businessName]) ?>
<header class="portal-heading"><p class="eyebrow">CLIENT PORTAL</p><h1>Welcome, <?= esc($customer['name']) ?></h1><p>Your requests, quotes, and active project updates in one private workspace.</p></header>
<section class="portal-metrics" aria-label="Account summary"><div><span>Requests</span><strong><?= $requestCount ?></strong></div><div><span>Quotes</span><strong><?= $quoteCount ?></strong></div><div><span>Projects</span><strong><?= $projectCount ?></strong></div></section>
<div class="portal-dashboard-grid">
    <section class="portal-list"><div class="portal-section-heading"><h2>Projects</h2><span>Latest updates</span></div><?php if ($projects === []): ?><p class="portal-empty">No projects are available yet.</p><?php else: ?><?php foreach ($projects as $project): ?><a class="portal-list-row" href="/portal/projects/<?= (int) $project['id'] ?>"><span><strong><?= esc($project['name']) ?></strong><small><?= esc($project['project_number']) ?></small></span><span class="portal-status"><?= esc(\App\Models\ProjectModel::STATUSES[$project['status']] ?? ucfirst($project['status'])) ?></span></a><?php endforeach ?><?php endif ?></section>
    <section class="portal-list"><div class="portal-section-heading"><h2>Quotes</h2><span>Sent by the studio</span></div><?php if ($quotes === []): ?><p class="portal-empty">No quotes are available yet.</p><?php else: ?><?php foreach ($quotes as $quote): ?><a class="portal-list-row" href="/portal/quotes/<?= (int) $quote['id'] ?>"><span><strong><?= esc($quote['quote_number']) ?></strong><small><?= esc($quote['currency_code']) ?> <?= esc(number_format((float) $quote['total'], 2)) ?></small></span><span class="portal-status"><?= esc(\App\Models\QuoteModel::STATUSES[$quote['status']] ?? ucfirst($quote['status'])) ?></span></a><?php endforeach ?><?php endif ?></section>
    <section class="portal-list portal-list-wide"><div class="portal-section-heading"><h2>Quote requests</h2><span>Your submitted briefs</span></div><?php if ($requests === []): ?><p class="portal-empty">No quote requests are linked to this account.</p><?php else: ?><?php foreach ($requests as $request): ?><a class="portal-list-row" href="/portal/requests/<?= (int) $request['id'] ?>"><span><strong><?= esc($request['project_summary']) ?></strong><small><?= esc($request['reference_number']) ?> &middot; <?= esc(substr((string) $request['created_at'], 0, 10)) ?></small></span><span class="portal-status"><?= esc(\App\Models\QuoteRequestModel::STATUSES[$request['status']] ?? ucfirst($request['status'])) ?></span></a><?php endforeach ?><?php endif ?></section>
</div>
<?= view('portal/partials/shell_end', ['businessName' => $businessName, 'contactEmail' => $contactEmail]) ?>
