<?php $formItems = old('items', $items); $errors = session('errors') ?? []; ?>
<?= view('admin/partials/shell_start', ['pageTitle' => 'Edit quote', 'activeSection' => 'quotes', 'businessName' => $businessName]) ?>
<main class="admin-main admin-main-wide">
    <a class="admin-back-link" href="/admin/quotes">&larr; Quotes</a>
    <div class="admin-page-heading admin-quote-heading"><div><p class="admin-kicker"><?= esc($quote['quote_number']) ?> &middot; VERSION <?= (int) $quote['version'] ?></p><h1><?= esc($quote['customer_business_name'] ?: $quote['customer_name']) ?></h1><p><?= esc($quote['customer_name']) ?> &middot; <?= esc($quote['customer_email']) ?><?php if ($request): ?> &middot; <a href="/admin/quote-requests/<?= (int) $request['id'] ?>"><?= esc($request['reference_number']) ?></a><?php endif ?></p></div><span class="admin-status admin-status-<?= esc($quote['status'], 'attr') ?>"><?= esc($statuses[$quote['status']] ?? ucfirst($quote['status'])) ?></span></div>
    <?php if (session('message')): ?><div class="notice" role="status"><?= esc(session('message')) ?></div><?php endif ?>
    <?php if ($errors !== []): ?><div class="notice notice-error" role="alert">Please review the quote fields and line items.</div><?php endif ?>
    <form class="admin-quote-editor" action="/admin/quotes/<?= (int) $quote['id'] ?>" method="post" data-quote-editor>
        <?= csrf_field() ?>
        <div class="admin-quote-editor-main">
            <section class="admin-quote-panel"><div class="admin-panel-heading"><h2>Quote details</h2><p>Dates, currency, and current workflow state.</p></div><div class="form-grid admin-quote-metadata"><div class="form-row"><label for="quote-date">Quote date</label><input id="quote-date" type="date" name="quote_date" value="<?= esc(old('quote_date', $quote['quote_date']), 'attr') ?>"></div><div class="form-row"><label for="expires-on">Expires on</label><input id="expires-on" type="date" name="expires_on" value="<?= esc(old('expires_on', $quote['expires_on']), 'attr') ?>"><?php if (isset($errors['expires_on'])): ?><p class="field-error"><?= esc($errors['expires_on']) ?></p><?php endif ?></div><div class="form-row"><label for="currency-code">Currency</label><input id="currency-code" name="currency_code" maxlength="3" value="<?= esc(old('currency_code', $quote['currency_code']), 'attr') ?>"></div><div class="form-row"><label for="quote-status">Status</label><select id="quote-status" name="status"><?php foreach ($statuses as $value => $label): ?><option value="<?= esc($value, 'attr') ?>" <?= old('status', $quote['status']) === $value ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></div></div></section>
            <section class="admin-quote-panel"><div class="admin-panel-heading admin-panel-heading-action"><div><h2>Line items</h2><p>Use deliverables and prices that reflect the actual scope.</p></div><button class="admin-secondary-action" type="button" data-add-line>+ Add line</button></div><?php if (isset($errors['items'])): ?><p class="field-error"><?= esc($errors['items']) ?></p><?php endif ?><div class="admin-line-items" data-line-items><?php foreach (array_values($formItems) as $index => $item): ?><?= view('admin/quotes/_line_item', ['index' => $index, 'item' => $item, 'errors' => $errors]) ?><?php endforeach ?></div><template data-line-template><?= view('admin/quotes/_line_item', ['index' => '__INDEX__', 'item' => ['description' => '', 'details' => '', 'quantity' => '1.00', 'unit_price' => '0.00'], 'errors' => []]) ?></template></section>
            <section class="admin-quote-panel"><div class="admin-panel-heading"><h2>Terms and notes</h2><p>Customer-facing conditions and additional context.</p></div><div class="form-row"><label for="quote-terms">Terms</label><textarea id="quote-terms" name="terms" rows="9" maxlength="10000"><?= esc(old('terms', $quote['terms'] ?? '')) ?></textarea></div><div class="form-row"><label for="quote-notes">Notes shown to customer</label><textarea id="quote-notes" name="notes" rows="5" maxlength="5000"><?= esc(old('notes', $quote['notes'] ?? '')) ?></textarea></div></section>
        </div>
        <aside class="admin-quote-totals"><h2>Pricing summary</h2><div class="form-row"><label for="discount-amount">Discount amount</label><input id="discount-amount" data-discount type="number" min="0" step="0.01" name="discount_amount" value="<?= esc(old('discount_amount', $quote['discount_amount']), 'attr') ?>"></div><div class="form-row"><label for="tax-rate">Tax rate (%)</label><input id="tax-rate" data-tax type="number" min="0" max="100" step="0.001" name="tax_rate" value="<?= esc(old('tax_rate', $quote['tax_rate']), 'attr') ?>"></div><div class="form-row"><label for="deposit-percentage">Deposit (%)</label><input id="deposit-percentage" data-deposit type="number" min="0" max="100" step="0.01" name="deposit_percentage" value="<?= esc(old('deposit_percentage', $quote['deposit_percentage']), 'attr') ?>"></div><dl class="admin-live-totals"><dt>Subtotal</dt><dd data-subtotal><?= esc(number_format((float) $quote['subtotal'], 2)) ?></dd><dt>Discount</dt><dd data-discount-total>-<?= esc(number_format((float) $quote['discount_amount'], 2)) ?></dd><dt>Tax</dt><dd data-tax-total><?= esc(number_format((float) $quote['tax_amount'], 2)) ?></dd><dt class="total">Total</dt><dd class="total" data-total><?= esc(number_format((float) $quote['total'], 2)) ?></dd><dt>Deposit due</dt><dd data-deposit-total><?= esc(number_format((float) $quote['deposit_amount'], 2)) ?></dd></dl><button class="admin-primary-action" type="submit">Save new revision</button><?php if (in_array($quote['status'], \App\Models\QuoteModel::PUBLIC_STATUSES, true)): ?><a class="admin-preview-link" href="/proposal/<?= esc($quote['access_token'], 'attr') ?>" target="_blank" rel="noopener">Open secure preview &nearr;</a><?php else: ?><p class="admin-delivery-state">Mark this quote ready to enable its secure preview.</p><?php endif ?><p class="admin-delivery-state">Email delivery: <?= esc(str_replace('_', ' ', $quote['delivery_status'])) ?></p></aside>
    </form>
    <div class="admin-quote-lower"><section><h2>Status history</h2><?php foreach ($history as $entry): ?><article><span><?= esc($entry['created_at']) ?></span><strong><?= esc($entry['from_status'] ? ($statuses[$entry['from_status']] ?? $entry['from_status']) . ' to ' : '') ?><?= esc($statuses[$entry['to_status']] ?? $entry['to_status']) ?></strong><?php if ($entry['note']): ?><p><?= esc($entry['note']) ?></p><?php endif ?></article><?php endforeach ?></section><section><h2>Revisions</h2><p><?= count($versions) ?> immutable <?= count($versions) === 1 ? 'snapshot' : 'snapshots' ?> stored.</p></section><section class="admin-send-panel"><h2>Delivery</h2><p>Mark the quote ready, save it, then send the secure link by email.</p><form action="/admin/quotes/<?= (int) $quote['id'] ?>/send" method="post"><?= csrf_field() ?><button class="admin-primary-action" type="submit" <?= $quote['status'] !== 'ready' ? 'disabled' : '' ?>>Send quote</button></form></section></div>
</main>
<script src="<?= esc(base_url('assets/js/quote-editor.js'), 'attr') ?>" defer></script>
<?= view('admin/partials/shell_end') ?>
